services:
    _defaults:
        autowire: true
        autoconfigure: true

    Codeplace\SettingsBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Model/'
            - '../../CodeplaceSettingsBundle.php'